-- HoosRadar initial schema — DESIGN DRAFT
--
-- Explained in event-model.md. This file is the reviewable shape of the data
-- model; the executable migration is generated by drizzle-kit in Milestone 1
-- (see ADR 0002) and should match this.
--
-- Targets PostgreSQL 16.

-- ---------------------------------------------------------------------------
-- Sources
-- ---------------------------------------------------------------------------

CREATE TYPE collection_method AS ENUM ('ics', 'rss', 'atom', 'json_api', 'html');

CREATE TABLE sources (
    id                  text PRIMARY KEY,            -- slug, e.g. 'uva-main-calendar'
    display_name        text        NOT NULL,
    owner               text        NOT NULL,        -- who runs the source
    homepage_url        text        NOT NULL,
    feed_url            text,                        -- null for html scraping
    method              collection_method NOT NULL,

    -- Source policy (OVERVIEW.md section 9). A source with no terms review is
    -- not eligible to be enabled.
    terms_url           text,
    terms_reviewed_at   timestamptz,
    terms_notes         text,
    retain_raw_payload  boolean     NOT NULL DEFAULT false,
    raw_retention_days  integer     NOT NULL DEFAULT 7,
    contact_email       text,                        -- removal-request contact

    -- Scheduling (ADR 0004)
    interval_seconds    integer     NOT NULL DEFAULT 3600,
    next_run_at         timestamptz NOT NULL DEFAULT now(),
    consecutive_failures integer    NOT NULL DEFAULT 0,

    enabled             boolean     NOT NULL DEFAULT false,
    disabled_reason     text,

    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT enabled_requires_terms_review
        CHECK (enabled = false OR terms_reviewed_at IS NOT NULL),
    CONSTRAINT positive_interval CHECK (interval_seconds > 0)
);

CREATE INDEX sources_due_idx ON sources (next_run_at) WHERE enabled;

-- ---------------------------------------------------------------------------
-- Ingestion runs  (job record + observability record)
-- ---------------------------------------------------------------------------

CREATE TYPE run_status AS ENUM ('running', 'succeeded', 'partial', 'failed');

CREATE TABLE ingestion_runs (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id        text        NOT NULL REFERENCES sources (id) ON DELETE CASCADE,
    status           run_status  NOT NULL DEFAULT 'running',
    started_at       timestamptz NOT NULL DEFAULT now(),
    finished_at      timestamptz,

    records_seen     integer     NOT NULL DEFAULT 0,
    records_created  integer     NOT NULL DEFAULT 0,
    records_updated  integer     NOT NULL DEFAULT 0,
    records_skipped  integer     NOT NULL DEFAULT 0,  -- malformed, logged, skipped
    records_failed   integer     NOT NULL DEFAULT 0,

    attempt          integer     NOT NULL DEFAULT 1,
    error_kind       text,                            -- 'fetch' | 'parse' | 'persist'
    error_summary    text,                            -- never contains secrets

    CONSTRAINT finished_runs_have_end
        CHECK (status = 'running' OR finished_at IS NOT NULL)
);

CREATE INDEX ingestion_runs_source_time_idx
    ON ingestion_runs (source_id, started_at DESC);

-- ---------------------------------------------------------------------------
-- Raw snapshots  (bounded retention, only where terms allow)
-- ---------------------------------------------------------------------------

CREATE TABLE raw_snapshots (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id        uuid        NOT NULL REFERENCES ingestion_runs (id) ON DELETE CASCADE,
    source_id     text        NOT NULL REFERENCES sources (id) ON DELETE CASCADE,
    fetched_at    timestamptz NOT NULL DEFAULT now(),
    http_status   integer,
    content_type  text,
    content_hash  text        NOT NULL,   -- always recorded
    byte_size     integer,
    payload       text,                   -- NULL when retention is not permitted
    retain_until  timestamptz NOT NULL
);

CREATE INDEX raw_snapshots_expiry_idx ON raw_snapshots (retain_until);
CREATE INDEX raw_snapshots_run_idx    ON raw_snapshots (run_id);

-- ---------------------------------------------------------------------------
-- Organizations
-- ---------------------------------------------------------------------------

CREATE TABLE organizations (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    normalized_name text        NOT NULL UNIQUE,  -- dedup key
    display_name    text        NOT NULL,         -- as the source wrote it
    homepage_url    text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Source events  (one row per event PER SOURCE — see event-model.md)
-- ---------------------------------------------------------------------------

CREATE TYPE event_status AS ENUM ('scheduled', 'cancelled', 'postponed');

CREATE TABLE source_events (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Provenance + idempotency
    source_id          text        NOT NULL REFERENCES sources (id) ON DELETE CASCADE,
    source_event_key   text        NOT NULL,   -- stable id from the source
    canonical_url      text        NOT NULL,   -- link back to the original
    first_run_id       uuid        REFERENCES ingestion_runs (id) ON DELETE SET NULL,
    last_run_id        uuid        REFERENCES ingestion_runs (id) ON DELETE SET NULL,

    -- Content
    title              text        NOT NULL,
    description        text,
    starts_at          timestamptz NOT NULL,
    ends_at            timestamptz,
    timezone           text        NOT NULL,   -- IANA name, e.g. 'America/New_York'
    is_all_day         boolean     NOT NULL DEFAULT false,

    venue_name         text,
    venue_address      text,
    latitude           numeric(9, 6),
    longitude          numeric(9, 6),

    organization_id    uuid        REFERENCES organizations (id) ON DELETE SET NULL,
    category_raw       text,                    -- source's own wording, unmapped
    tags               text[]      NOT NULL DEFAULT '{}',

    cost_text          text,
    is_free            boolean,                 -- NULL = source did not say
    accessibility_notes text,

    status             event_status NOT NULL DEFAULT 'scheduled',

    -- Freshness (see event-model.md for why these are three separate columns)
    source_published_at     timestamptz,
    source_updated_at       timestamptz,
    first_seen_at           timestamptz NOT NULL DEFAULT now(),
    last_seen_at            timestamptz NOT NULL DEFAULT now(),
    last_synced_at          timestamptz NOT NULL DEFAULT now(),
    last_material_change_at timestamptz NOT NULL DEFAULT now(),
    content_hash            text        NOT NULL,

    -- Weighted full-text search, maintained by Postgres
    search_vector tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')),      'A') ||
        setweight(to_tsvector('english', coalesce(venue_name, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(category_raw, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(description, '')), 'C')
    ) STORED,

    CONSTRAINT idempotent_import UNIQUE (source_id, source_event_key),
    CONSTRAINT ends_after_starts CHECK (ends_at IS NULL OR ends_at >= starts_at),
    CONSTRAINT coords_together CHECK (
        (latitude IS NULL) = (longitude IS NULL)
    )
);

CREATE INDEX source_events_upcoming_idx
    ON source_events (starts_at)
    WHERE status <> 'cancelled';
CREATE INDEX source_events_search_idx ON source_events USING gin (search_vector);
CREATE INDEX source_events_org_idx    ON source_events (organization_id);
CREATE INDEX source_events_stale_idx  ON source_events (source_id, last_synced_at);

-- ---------------------------------------------------------------------------
-- Deduplication  (grouping only — never mutates or deletes source_events)
-- ---------------------------------------------------------------------------

CREATE TYPE match_strategy AS ENUM (
    'exact_key',
    'canonical_url',
    'deterministic_similarity',
    'manual'
);

CREATE TABLE duplicate_groups (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    primary_event_id uuid REFERENCES source_events (id) ON DELETE SET NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    reviewed_at      timestamptz,
    reviewed_by      text,
    review_note      text
);

CREATE TABLE duplicate_group_members (
    group_id    uuid           NOT NULL REFERENCES duplicate_groups (id) ON DELETE CASCADE,
    event_id    uuid           NOT NULL REFERENCES source_events (id)   ON DELETE CASCADE,
    added_by    match_strategy NOT NULL,
    match_score numeric(4, 3),               -- only for deterministic_similarity
    added_at    timestamptz    NOT NULL DEFAULT now(),
    removed_at  timestamptz,                 -- unmerge = set this, never DELETE
    removed_reason text,

    PRIMARY KEY (group_id, event_id)
);

-- An event belongs to at most one *active* group.
CREATE UNIQUE INDEX duplicate_members_one_active_group_idx
    ON duplicate_group_members (event_id)
    WHERE removed_at IS NULL;

-- ---------------------------------------------------------------------------
-- Corrections  (tracked, never a destructive edit to imported data)
-- ---------------------------------------------------------------------------

CREATE TYPE correction_status AS ENUM ('open', 'accepted', 'rejected');

CREATE TABLE corrections (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id      uuid        NOT NULL REFERENCES source_events (id) ON DELETE CASCADE,
    field         text        NOT NULL,   -- which field is disputed
    reported_value text,                  -- what the reporter says it should be
    reason        text,
    status        correction_status NOT NULL DEFAULT 'open',
    created_at    timestamptz NOT NULL DEFAULT now(),
    resolved_at   timestamptz,
    resolved_by   text,
    resolution_note text
);

CREATE INDEX corrections_open_idx ON corrections (event_id) WHERE status = 'open';
